import { Inter } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "./authcontext/authcontext";
import Hero from "@/components/hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Order with Friends",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
