/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cVysif1zvxo
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Eczar } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

eczar({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts

**/

import Image from "next/image";

export function Aboutdev() {
  return (
    <div className="flex flex-col gap-12 w-full">
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                About the App
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-blue-600">
                Bringing a shift to ordering at restaurants
              </h2>
              <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our app is designed to make ordering not a chore with awkward
                interactions with waiters asking &quot;Hey what&apos;s good
                here&quot; and &quot;hmmmmmmmmmmmmm&quot;. We want to connect
                the kitchen to the patron, let them know which dishes are the
                most ordered and recommend your best.
              </p>
            </div>
            <div className="space-y-4">
              <div className="grid gap-6">
                <div>
                  <h3 className="text-xl font-bold">
                    Effortless Table Management
                  </h3>
                  <p className="text-muted-foreground">
                    Table data is instantly updated to your screens with almost
                    zero delay. Track and see pending and completed orders
                  </p>
                </div>
                <div>
                  <h3 className="text-xl font-bold">Collaborative Workspace</h3>
                  <p className="text-muted-foreground">
                    Upgrade your waiters with phones/tablets and create a
                    collaborative workspace with the kitchens, waiters and
                    patrons all on the same page
                  </p>
                </div>
                <div>
                  <h3 className="text-xl font-bold">
                    Upcoming Loyalty Features and Payment Integrations
                  </h3>
                  <p className="text-muted-foreground">
                    Loyalty features for regular users, my idea is to use
                    Machine Learning to track their orders (with consent) and
                    recommend their favorite dishes. <br />
                    Payment integration is a challenge I will be working on for
                    a while, since I show split bills for everyone.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container px-4 md:px-6 grid gap-12 lg:grid-cols-2 lg:gap-24">
          <div className="space-y-4">
            <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
              Meet the Developer
            </div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-blue-600">
              Hello, I&apos;m Krish
            </h2>
            <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              I built this app because my friends and I always had a hard time
              calculating splits and our only possible solutions were a straight
              split or we pull out a calculator and fret. Honestly, the straight
              split was fine but the vegetarians always carried the bill for us
              non-vegetarians
            </p>
            <div className="grid gap-4">
              <div className="flex items-center gap-4">
                <div className="bg-muted rounded-full w-12 h-12 flex items-center justify-center">
                  <TerminalIcon className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="text-lg font-medium">Krish Verma</h4>
                  <p className="text-muted-foreground">Lone (Lead) Developer</p>
                </div>
              </div>
              <div className="grid gap-1">
                <h4 className="text-sm font-medium">About the Developer</h4>
                <p className="text-muted-foreground">
                  Hello, I&apos;m a developer, I like solving problems and I
                  hate, I mean really hate Java. Currently dabbling in cloud
                  computing and pursuing machine learning as a hobby (get a
                  life??) but also a keen contemporary history enjoyer and I
                  like debating
                </p>
              </div>
            </div>
          </div>
          <div className="">
            <Image
              src="/turn-down.png"
              width={100}
              height={100}
              alt="bruh"
              className="lg:absolute lg:left-[1000px] lg:top-[850px] "
            />
            <p className="lg:absolute lg:left-[1120px] lg:top-[840px] text-muted-foreground">
              Yep, that&apos;s me at BITSMUN&apos;23 Hyderabad
            </p>
            <Image
              src="/krish.png"
              width={250}
              height={250}
              alt="John Doe"
              className="mx-auto rounded-xl object-cover"
            />
          </div>
        </div>
      </section>
    </div>
  );
}

function TerminalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 17 10 11 4 5" />
      <line x1="12" x2="20" y1="19" y2="19" />
    </svg>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
